# -*- coding: utf-8 -*-
"""v2.10.0 — إضافة 50 عبارة جديدة بكل اللغات الست (بلا تكرار مع المكتبة الحالية)"""
import json

P = "shared/uplift-quotes.json"
d = json.load(open(P, encoding="utf-8"))
assert len(d) == 65, f"expected 65, got {len(d)}"

# (cat, au, ar, fr, en, tr, ru, zh)
NEW = [
("religious", "قرآن كريم — التوبة",
 "﴿لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا﴾",
 "«Ne t'afflige pas : Allah est avec nous» (Sourate At-Tawba)",
 "«Do not grieve; indeed Allah is with us» (Surah At-Tawba)",
 "«Üzülme, Allah bizimledir» (Tevbe Suresi)",
 "«Не печалься, ведь Аллах — с нами» (сура «Ат-Тауба»)",
 "「你不要忧愁，真主确是同我们在一起的」（《忏悔章》）"),
("religious", "قرآن كريم — آل عمران",
 "﴿وَمَن يَعْتَصِم بِاللَّهِ فَقَدْ هُدِيَ إِلَىٰ صِرَاطٍ مُّسْتَقِيمٍ﴾",
 "«Quiconque s'attache à Allah est guidé vers un droit chemin» (Sourate Âl-Imran)",
 "«Whoever holds firmly to Allah is guided to a straight path» (Surah Al-Imran)",
 "«Kim Allah'a sımsıkı tutunursa, o dosdoğru yola iletilmiştir» (Âl-i İmrân Suresi)",
 "«Кто крепко держится за Аллаха, тот ведён прямым путём» (сура «Семейство Имрана»)",
 "「谁抓紧真主，谁已受引导于正道」（《仪姆兰的家属章》）"),
("religious", "قرآن كريم — آل عمران",
 "﴿وَاللَّهُ يُحِبُّ الصَّابِرِينَ﴾",
 "«Et Allah aime les endurants» (Sourate Âl-Imran)",
 "«And Allah loves the patient ones» (Surah Al-Imran)",
 "«Allah, sabredenleri sever» (Âl-i İmrân Suresi)",
 "«Аллах любит терпеливых» (сура «Семейство Имрана»)",
 "「真主喜爱坚忍的人」（《仪姆兰的家属章》）"),
("religious", "قرآن كريم — ق",
 "﴿نَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ﴾",
 "«Nous sommes plus proche de lui que sa veine jugulaire» (Sourate Qaf)",
 "«We are closer to him than his jugular vein» (Surah Qaf)",
 "«Biz ona şah damarından daha yakınız» (Kâf Suresi)",
 "«Мы ближе к нему, чем яремная вена» (сура «Каф»)",
 "「我比他的命脉还近于他」（《戛弗章》）"),
("religious", "قرآن كريم — الشعراء",
 "﴿وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ﴾",
 "«Et quand je suis malade, c'est Lui qui me guérit» (Sourate Ach-Chou'ara)",
 "«And when I am ill, it is He who cures me» (Surah Ash-Shu'ara)",
 "«Hastalandığımda ise O beni iyileştirir» (Şuarâ Suresi)",
 "«А когда я заболеваю, Он меня исцеляет» (сура «Поэтов»)",
 "「我患病时，是他使我痊愈」（《众诗人章》）"),
("religious", "قرآن كريم — إبراهيم",
 "﴿لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ﴾",
 "«Si vous êtes reconnaissants, Je vous donnerai davantage» (Sourate Ibrahim)",
 "«If you are grateful, I will surely increase you» (Surah Ibrahim)",
 "«And olsun, şükrederseniz size elbette artırırım» (İbrâhîm Suresi)",
 "«Если вы будете благодарны, Я непременно умножу вам» (сура «Ибрахим»)",
 "「如果你们感谢，我誓必对你们恩上加恩」（《易卜拉欣章》）"),
("religious", "قرآن كريم — غافر",
 "﴿وَأُفَوِّضُ أَمْرِي إِلَى اللَّهِ إِنَّ اللَّهَ بَصِيرٌ بِالْعِبَادِ﴾",
 "«Je confie mon sort à Allah : Allah voit bien Ses serviteurs» (Sourate Ghafir)",
 "«I entrust my affair to Allah: Allah sees His servants» (Surah Ghafir)",
 "«İşimi Allah'a bırakıyorum. Şüphesiz Allah, kulları hakkıyla görür» (Mü'min Suresi)",
 "«Я вверяю своё дело Аллаху, ведь Аллах видит рабов» (сура «Гафир»)",
 "「我把我的事务托靠真主，真主确是明察众仆的」（《赦宥者章》）"),
("religious", "قرآن كريم — مريم",
 "﴿سَيَجْعَلُ لَهُمُ الرَّحْمَٰنُ وُدًّا﴾",
 "«Le Tout Miséricordieux créera pour eux un amour (dans les cœurs)» (Sourate Maryam)",
 "«The Most Merciful will appoint for them affection» (Surah Maryam)",
 "«Rahmân, onlar için (kalplerde) sevgi yaratacaktır» (Meryem Suresi)",
 "«Милосердный одарит их любовью» (сура «Марьям»)",
 "「至仁主必为他们在人们心中创造友爱」（《麦尔彦章》）"),
("religious", "حديث شريف — مسلم",
 "«الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ وَفِي كُلٍّ خَيْرٌ»",
 "«Le croyant fort est meilleur et plus aimé d'Allah que le croyant faible, et il y a du bien en chacun» (Muslim)",
 "«The strong believer is better and more beloved to Allah than the weak believer, though in each there is good» (Muslim)",
 "«Güçlü mü'min, zayıf mü'minden daha hayırlı ve Allah'a daha sevimlidir; ama her birinde hayır vardır» (Müslim)",
 "«Сильный верующий лучше и любезнее Аллаху, чем слабый, хотя в каждом есть благо» (Муслим)",
 "「坚强的信士比软弱的信士更好、更受真主喜爱，但每个人身上都有福分」（穆斯林圣训）"),
("religious", "حديث شريف — الترمذي",
 "«الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ»",
 "«Les miséricordieux recevront la miséricorde du Tout Miséricordieux : soyez miséricordieux envers ceux qui sont sur terre» (Tirmidhi)",
 "«The merciful will be shown mercy by the Most Merciful: be merciful to those on earth» (Tirmidhi)",
 "«Merhametlilere Rahmân merhamet eder. Yerdekilere merhamet edin ki göktekiler size merhamet etsin» (Tirmizî)",
 "«Милостивых помилует Милостивый: будьте милосердны к тем, кто на земле» (Тирмизи)",
 "「慈爱者得至仁主慈爱。你们慈爱大地上的人们，天上的主就会慈爱你们」（提尔米济圣训）"),
("religious", "دعاء نبوي — ابن ماجه",
 "«اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ»",
 "«Ô Allah, je Te demande le bien-être» (Ibn Majah)",
 "«O Allah, I ask You for well-being» (Ibn Majah)",
 "«Allah'ım, Senden afiyet diliyorum» (İbn Mâce)",
 "«О Аллах, я прошу у Тебя благополучия» (Ибн Маджa)",
 "「主啊，我向你祈求平安健康」（伊本·马哲圣训）"),
("religious", "ذكر من السنة",
 "«لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ»",
 "«Il n'y a de force ni de puissance qu'auprès d'Allah»",
 "«There is no power and no strength except with Allah»",
 "«La havle ve la kuvvete illâ billâh — güç ve kuvvet ancak Allah'ın yardımı iledir»",
 "«Нет мощи и силы, кроме как у Аллаха»",
 "「无法无力，唯凭真主」"),
("religious", "قرآن كريم — التوبة",
 "﴿إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ﴾",
 "«Allah ne laisse jamais perdre la récompense des bienfaisants» (Sourate At-Tawba)",
 "«Allah does not waste the reward of the doers of good» (Surah At-Tawba)",
 "«Allah, iyilik yapanların karşılığını zayi etmez» (Tevbe Suresi)",
 "«Аллах не губит награду творящих добро» (сура «Ат-Тауба»)",
 "「真主一定不使行善者的努力徒劳无酬」（《忏悔章》）"),
("religious", "قرآن كريم — الطلاق",
 "﴿وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ﴾",
 "«Et Il lui accorde une subsistance par où il ne compte pas» (Sourate At-Talaq)",
 "«And He provides for him from where he does not expect» (Surah At-Talaq)",
 "«Ve onu beklemediği yerden rızıklandırır» (Talâk Suresi)",
 "«И наделяет его уделом оттуда, откуда он даже не предполагает» (сура «Ат-Талак»)",
 "「并且从他料想不到的地方供给他」（《离婚章》）"),
("religious", "قرآن كريم — النمل",
 "﴿أَمَّن يُجِيبُ الْمُضْطَرَّ إِذَا دَعَاهُ﴾",
 "«Qui donc répond à l'angoissé quand il L'invoque ?» (Sourate An-Naml)",
 "«Who responds to the distressed one when he calls upon Him?» (Surah An-Naml)",
 "«Sıkıntıya düşenin duasını kabul eden O mudur?» (Neml Suresi)",
 "«Или Тот, Кто отвечает нуждающемуся, когда он взывает?» (сура «Ан-Намль»)",
 "「还是那应答受难者的祈祷而解救他的呢？」（《蚂蚁章》）"),
("religious", "قرآن كريم — الضحى",
 "﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ﴾",
 "«Et ton Seigneur te donnera bientôt, et tu seras satisfait» (Sourate Ad-Duha)",
 "«And your Lord is going to give you, and you will be satisfied» (Surah Ad-Duha)",
 "«Rabbin sana verecek ve sen de hoşnut kalacaksın» (Duhâ Suresi)",
 "«И твой Господь обязательно дарует тебе, и ты будешь доволен» (сура «Ад-Духа»)",
 "「你的主将来赏赐你，以至你喜悦」（《上午章》）"),
("social", "حكمة اجتماعية",
 "خطوة صغيرة كل يوم تصنع مسافة كبيرة مع الوقت",
 "Un petit pas chaque jour devient une grande distance avec le temps",
 "One small step each day becomes a great distance over time",
 "Her gün atılan küçük bir adım, zamanla büyük bir mesafeye dönüşür",
 "Маленький шаг каждый день со временем превращается в большой путь",
 "每天一小步，日积月累就是一大段路"),
("social", "حكمة اجتماعية",
 "التعب الذي تشعر به علامة على أنك تحاول، لا أنك فاشل",
 "La fatigue que tu ressens est la preuve que tu essaies, pas que tu échoues",
 "The tiredness you feel is proof that you are trying, not that you are failing",
 "Hissettiğin yorgunluk, denediğinin işaretidir; başarısız olduğunun değil",
 "Усталость, которую ты чувствуешь, — знак того, что ты стараешься, а не провалился",
 "你感到的疲惫，说明你在努力，而不是失败"),
("social", "حكمة اجتماعية",
 "استمع لجسدك: الراحة جزء من العلاج وليست ترفًا",
 "Écoute ton corps : le repos fait partie du soin, ce n'est pas un luxe",
 "Listen to your body: rest is part of the treatment, not a luxury",
 "Vücudunu dinle: Dinlenmek tedavinin bir parçasıdır, lüks değil",
 "Слушай своё тело: отдых — часть лечения, а не роскошь",
 "倾听身体的声音：休息是治疗的一部分，不是奢侈"),
("social", "رسالة للمتضررين",
 "الكارثة لا تحدد نهايتك؛ إنها فصلٌ في قصتك، وليست القصة كلها",
 "La catastrophe ne définit pas ta fin : c'est un chapitre de ton histoire, pas toute l'histoire",
 "The disaster does not define your end: it is a chapter of your story, not the whole story",
 "Felaket sonun değildir; hikâyendeki bir bölümdür, hikâyenin tamamı değil",
 "Катастрофа не определяет твой конец; это лишь глава твоей истории, но не вся история",
 "灾难不能定义你的结局；它只是你故事中的一章，而不是全部"),
("social", "رسالة للمتضررين",
 "أعد بناء روتينك الصغير: كوب شاي، نافذة مفتوحة، وصلاة في وقتها",
 "Reconstruis ta petite routine : une tasse de thé, une fenêtre ouverte, une prière à l'heure",
 "Rebuild your little routine: a cup of tea, an open window, a prayer on time",
 "Küçük rutinini yeniden kur: bir bardak çay, açık bir pencere ve vaktinde bir namaz",
 "Восстанови свой маленький распорядок: чашка чая, открытое окно и молитва вовремя",
 "重建你的日常小事：一杯茶、一扇开着的窗、一次准时的礼拜"),
("social", "حكمة اجتماعية",
 "لا تستحِ من دموعك؛ الأعين التي تبكي قلوبها حية",
 "N'aie pas honte de tes larmes : les yeux qui pleurent ont un cœur vivant",
 "Do not be ashamed of your tears: eyes that cry have a living heart",
 "Gözyaşlarından utanma; ağlayan gözlerin kalbi canlı demektir",
 "Не стыдись слёз; плачущие глаза — признак живого сердца",
 "不要为眼泪感到羞耻；会流泪的眼睛，说明心还活着"),
("social", "حكمة اجتماعية",
 "تحدث عن شعورك ولو بكلمة واحدة؛ الصمت الطويل ثقيل على القلب",
 "Parle de ce que tu ressens, ne serait-ce qu'un mot : le long silence pèse sur le cœur",
 "Speak about how you feel, even one word: long silence weighs on the heart",
 "Duygularından bahset, tek kelime bile olsa; uzun sessizlik kalbe ağır gelir",
 "Говори о своих чувствах, хотя бы одним словом; долгое молчание тяжело для сердца",
 "说出你的感受，哪怕只有一个词；长久的沉默压在心上"),
("social", "رسالة للمتضررين",
 "بيتك المحترق يحتاج صوتك الهادئ — لا تؤجل العودة إليه",
 "Ta maison brûlée a besoin de ta voix calme — ne remets pas à plus tard d'y revenir",
 "Your burned home needs your calm voice — do not delay returning to it",
 "Yanan evin, sakin sesine ihtiyaç duyuyor — ona dönmeyi erteleme",
 "Твой сгоревший дом ждёт твоего спокойного голоса — не откладывай возвращение",
 "你被烧毁的家需要你平静的声音——不要推迟回去的脚步"),
("social", "حكمة اجتماعية",
 "الغضب بعد الكارثة طبيعي؛ أعطِ نفسك إذنًا بالشعور ثم اتركه يمر",
 "La colère après une catastrophe est naturelle : permets-toi de ressentir, puis laisse passer",
 "Anger after a disaster is natural: allow yourself to feel, then let it pass",
 "Felaketten sonraki öfke doğaldır; kendine hissetme izni ver, sonra geçmesine izin ver",
 "Гнев после катастрофы нормален; позволь себе чувствовать, потом позволь этому пройти",
 "灾后的愤怒很正常；允许自己去感受，再让它慢慢过去"),
("social", "رسالة للمتضررين",
 "عانق أطفالك اليوم؛ احتضانهم دواءٌ لهم ولك معًا",
 "Embrasse tes enfants aujourd'hui : leur étreinte est un remède pour eux et pour toi",
 "Hug your children today: their embrace is medicine for them and for you",
 "Bugün çocuklarını kucakla; onların kucaklaşması hem onlara hem sana şifa olsun",
 "Обними своих детей сегодня; их объятия — лекарство и для них, и для тебя",
 "今天抱抱你的孩子；拥抱对他们和你都是良药"),
("social", "حكمة اجتماعية",
 "من يساعدك لا يرحمك؛ يكرّمك — اقبل العون ورفعة",
 "Celui qui t'aide ne te plaint pas : il te respecte — accepte l'aide dignement",
 "The one who helps you does not pity you: they honour you — accept help with dignity",
 "Sana yardım eden sana acımıyor; sana değer veriyor. Yardımı kabul et, başını dik tut",
 "Тот, кто помогает тебе, не жалеет тебя — он уважает тебя. Прими помощь с достоинством",
 "帮助你的人不是可怜你，而是尊重你；坦然接受帮助，挺直腰杆"),
("social", "حكمة اجتماعية",
 "النوم الجيد ليس رفاهية بعد الكارثة؛ إنه أول خطوات الإعمار",
 "Bien dormir n'est pas un luxe après une catastrophe : c'est le premier pas de la reconstruction",
 "Good sleep is not a luxury after a disaster: it is the first step of rebuilding",
 "Felaketten sonra iyi uyku bir lüks değildir; yeniden inşanın ilk adımıdır",
 "Хороший сон после катастрофы — не роскошь; это первые шаги восстановления",
 "灾后睡个好觉不是奢侈；这是重建的第一步"),
("social", "حكمة اجتماعية",
 "اكتب ثلاثة أشياء صغيرة خرجت سليمة اليوم؛ النظر للخير يطرد الظلام",
 "Écris trois petites choses qui sont restées intactes aujourd'hui : voir le bien chasse les ténèbres",
 "Write down three small things that survived today: looking at the good drives away darkness",
 "Bugün sağlam kalan üç küçük şeyi yaz; iyiliğe bakmak karanlığı dağıtır",
 "Запиши три маленькие вещи, которые остались целыми сегодня; взгляд на доброе разгоняет тьму",
 "写下今天平安无恙的三件小事；看见美好，就能驱散黑暗"),
("social", "حكمة اجتماعية",
 "لست بحاجة لكونك قويًّا طوال الوقت؛ قوي بما يكفي لطلب الغد",
 "Tu n'as pas besoin d'être fort tout le temps : tu l'es assez pour vouloir demain",
 "You do not need to be strong all the time: you are strong enough to want tomorrow",
 "Her an güçlü olmak zorunda değilsin; yarını isteyecek kadar güçlüsün",
 "Не обязательно быть сильным всё время; ты достаточно силён, чтобы хотеть завтрашнего дня",
 "你不必时时刻刻都坚强；你已有足够的力量去期待明天"),
("social", "حكمة اجتماعية",
 "الاستمرار في الصلاة والسكينة اليومية حبلٌ ينقذك من الموج العالي",
 "Persévérer dans la prière et le calme quotidien est une corde qui te sauve de la grande vague",
 "Persisting in prayer and daily calm is a rope that saves you from the high wave",
 "Namaza ve günlük sükûnete devam etmek, yüksek dalgadan kurtaran bir ip gibidir",
 "Продолжение молитвы и ежедневного спокойствия — верёвка, спасающая от высокой волны",
 "坚持礼拜与日常的安宁，是一根把你从巨浪中救起的绳索"),
("social", "حكمة اجتماعية",
 "جسدك يحمل آثار الموجعة؛ اجلس به بندّة كما تجلس بطفل خائف",
 "Ton corps porte les traces de la douleur : traite-le avec douceur, comme un enfant effrayé",
 "Your body carries traces of pain: treat it gently, like a frightened child",
 "Vücudun acının izlerini taşıyor; onunla, korkmuş bir çocukla oturur gibi şefkatle ol",
 "Твоё тело хранит следы боли; обращайся с ним нежно, как с испуганным ребёнком",
 "你的身体承载着伤痛的痕迹；像安抚受惊的孩子一样温柔待它"),
("social", "حكمة اجتماعية",
 "كل يوم جديد عقدة جديدة في حبل النجاة تُلفها بنفسك",
 "Chaque nouveau jour est un nouveau nœud dans ta corde de sauvetage, noué par toi",
 "Every new day is a new knot in your rescue rope, tied by your own hand",
 "Her yeni gün, kurtarma ipine kendi ellerinle bağladığın yeni bir düğümdür",
 "Каждый новый день — новый узел на спасательной верёвке, завязанный тобой",
 "每个新的一天，都是你亲手在救生绳上多打的一个结"),
("social", "رسالة للمتضررين",
 "ضحكة أطفالك في الخيمة أصدق دعاء صباح",
 "Le rire de tes enfants sous la tente est la plus sincère prière du matin",
 "The laughter of your children in the tent is the most sincere morning prayer",
 "Çadırdaki çocuklarının kahkahası en samimi sabah duasıdır",
 "Смех твоих детей в палатке — самая искренняя утренняя молитва",
 "帐篷里孩子们的笑声，是最真诚的清晨祈祷"),
("wisdom", "حكمة",
 "البحر الهادئ لا يصنع بحّارًا ماهرًا",
 "Une mer calme ne fait pas un marin habile",
 "A calm sea does not make a skilled sailor",
 "Sakin deniz, usta bir denizci yetiştirmez",
 "Спокойное море не делает искусным моряком",
 "平静的大海造就不出熟练的水手"),
("wisdom", "حكمة",
 "الشجرة التي مرّت بالعواصف جذورها أعمق",
 "L'arbre qui a traversé les tempêtes a des racines plus profondes",
 "The tree that weathered storms has deeper roots",
 "Fırtınalardan geçen ağacın kökleri daha derindir",
 "У дерева, пережившего бури, корни глубже",
 "经历过风暴的树，根扎得更深"),
("wisdom", "مثل شائع",
 "الذهب الذي يُختبر بالنار يخرج أصفى",
 "L'or éprouvé par le feu en sort plus pur",
 "Gold tested by fire comes out purer",
 "Ateşte sınanan altın daha saf çıkar",
 "Золото, проверенное огнём, выходит чище",
 "经过火炼的金子更纯净"),
("wisdom", "حكمة",
 "الحزن يمرّ كالسحاب، وآثاره الحسنة تبقى كالأرض",
 "Le chagrin passe comme un nuage, et ses beaux fruits restent comme la terre",
 "Sorrow passes like a cloud, and its good fruits remain like the earth",
 "Hüzün bulut gibi geçer; güzel etkileri toprak gibi kalır",
 "Печаль проходит, как облако, а её добрые плоды остаются, как земля",
 "悲伤如云飘过，它带来的成长却如大地长存"),
("wisdom", "حكمة",
 "من لا يمر بالضيق لا يعرف قيمة الفسحة",
 "Qui n'a connu l'étroitesse ne connaît la valeur de l'aisance",
 "Who has never known hardship does not know the value of ease",
 "Dara düşmeyen, ferahlığın değerini bilmez",
 "Кто не знал тесноты, не оценит простора",
 "没有经历狭窄的人，不懂得宽阔的可贵"),
("wisdom", "حكمة",
 "الأحجار التي يُرمى بها عليك قد تبني لك سلّمًا إن أحسنت وضعها",
 "Les pierres que l'on te jette peuvent devenir ton escalier si tu les empiles bien",
 "The stones thrown at you can become your staircase if you place them well",
 "İnsanların attığı taşlar, iyi yerleştirirsen sana bir merdiven olur",
 "Камни, что в тебя бросают, могут стать лестницей, если правильно их сложить",
 "别人扔来的石头，若善加摆放，可以成为你的阶梯"),
("wisdom", "حكمة",
 "النور لا يطلب إذنًا ليخترق شقّ الباب",
 "La lumière ne demande pas la permission pour passer par la fente de la porte",
 "Light does not ask permission to slip through the crack of the door",
 "Işık, kapının aralığından geçmek için izin istemez",
 "Свет не спрашивает разрешения, чтобы пробиться сквозь щель двери",
 "光不需要请求许可，就能穿过门缝"),
("wisdom", "حكمة",
 "من حسن اليقين أن الطريق المغلق اليوم ليس قصة النهاية",
 "Sache avec certitude : la route fermée aujourd'hui n'est pas la fin de l'histoire",
 "Know for certain: the road closed today is not the end of the story",
 "Şunu iyice bil: Bugün kapalı olan yol hikâyenin sonu değildir",
 "Знай твёрдо: закрытая сегодня дорога — не конец истории",
 "坚信一点：今天被堵住的路，并不是故事的结局"),
("wisdom", "حكمة",
 "المحنّ تمضي، والأخلاق التي تربّيت بها في المحنة تبقى",
 "Les épreuves passent ; le caractère forgé dans l'épreuve demeure",
 "Hardships pass; the character forged in trial remains",
 "Zorluklar geçer; sıkıntıda gösterdiğin güzel karakter kalır",
 "Трудности проходят, а характер, воспитанный в испытании, остаётся",
 "苦难终会过去；你在磨难中养成的品格会长存"),
("wisdom", "حكمة",
 "كل شتاءٍ يعلّمك كيف تصنع دفأك بنفسك",
 "Chaque hiver t'apprend à créer ta propre chaleur",
 "Every winter teaches you to create your own warmth",
 "Her kış, sıcağını kendin nasıl yaratacağını öğretir",
 "Каждая зима учит тебя создавать собственное тепло",
 "每一个寒冬都教会你如何自己创造温暖"),
("wisdom", "حكمة",
 "لا تُقارن موطئك الأول بموطئك الآن؛ قارنه بما كنت عليه بالأمس فقط",
 "Ne compare pas ton point de départ à où tu es maintenant : compare-toi seulement à hier",
 "Do not compare your starting point to where you are now; compare only to yesterday",
 "Bugünkü yerini başlangıçla değil; yalnızca dünkü halinle kıyasla",
 "Сравнивай себя не с началом пути, а только с тем, кем был вчера",
 "别拿现在的自己与最初相比；只和昨天比就够了"),
("wisdom", "حكمة",
 "إتقان السفينة الكبيرة إنما يُصقل في العواصف",
 "La maîtrise du grand navire se façonne dans les tempêtes",
 "The mastery of a great ship is forged in storms",
 "Büyük geminin ustalığı fırtınalarda olgunlaşır",
 "Мастерство большого корабля оттачивается в штормах",
 "大船的本领，正是风暴磨炼出来的"),
("wisdom", "حكمة صحية",
 "العقل السليم في جسد سليم — امشِ عشر دقائق اليوم من أجل مزاجك",
 "Un esprit sain dans un corps sain — marche dix minutes aujourd'hui pour ton humeur",
 "A sound mind in a sound body — walk ten minutes today for your mood",
 "Sağlam akıl sağlam vücuttadır — bugün ruh hâlin için on dakika yürü",
 "Здоровый дух в здоровом теле — пройдись сегодня десять минут ради настроения",
 "健全的头脑寓于健康的身体——今天就为心情散步十分钟"),
("wisdom", "حكمة اجتماعية",
 "قهوة الصباح تُهضم أسرع حين تُشرب مع ضيف",
 "Le café du matin passe mieux quand on le boit avec un invité",
 "Morning coffee goes down easier when shared with a guest",
 "Sabah kahvesi, bir misafirle içildiğinde daha keyifli olur",
 "Утренний кофе приятнее, когда пьёшь его с гостем",
 "与客人同饮的晨间咖啡，更有滋味"),
("wisdom", "حكمة",
 "أقوى الجسور تُبنى فوق أعمق الوديان",
 "Les ponts les plus solides sont bâtis sur les gorges les plus profondes",
 "The strongest bridges are built over the deepest ravines",
 "En güçlü köprüler, en derin vadilerin üzerine kurulur",
 "Самые крепкие мосты строят над самыми глубокими ущельями",
 "最坚固的桥，架在最深的峡谷之上"),
("wisdom", "حكمة",
 "الفجر لا يتفاوض مع الليل؛ هو يأتي ببساطة",
 "L'aube ne négocie pas avec la nuit : elle vient, tout simplement",
 "Dawn does not negotiate with the night: it simply comes",
 "Şafak geceyle pazarlık etmez; o sadece gelir",
 "Рассвет не торгуется с ночью — он просто приходит",
 "黎明不与黑夜讨价还价——它只是到来"),
]

assert len(NEW) == 50, len(NEW)
existing_ars = {q["ar"].strip() for q in d}
for row in NEW:
    if row[2].strip() in existing_ars:
        raise SystemExit(f"DUPLICATE detected: {row[2][:50]}")

for cat, au, ar, fr, en, tr, ru, zh in NEW:
    d.append({"cat": cat, "au": au, "ar": ar, "fr": fr, "en": en, "tr": tr, "ru": ru, "zh": zh})

json.dump(d, open(P, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(f"OK: library now has {len(d)} quotes (added {len(NEW)})")
