# -*- coding: utf-8 -*-
"""v2.10.0 — إضافة التركية والروسية والصينية للعبارات الـ65 الموجودة"""
import json

P = "shared/uplift-quotes.json"
d = json.load(open(P, encoding="utf-8"))
assert len(d) == 65, f"expected 65, got {len(d)}"

TR = [
"«İyi bilin ki, kalpler ancak Allah'ı anmakla huzur bulur» (Ra'd Suresi)",
"«Şüphesiz güçlükle beraber bir kolaylık vardır» (Şerh Suresi)",
"«Kim Allah'tan korkarsa, O ona bir çıkış yolu verir» (Talâk Suresi)",
"«Sabredenleri müjdele» (Bakara Suresi)",
"«Şüphesiz Allah sabredenlerle beraberdir» (Bakara Suresi)",
"«Olası ki hoşlanmadığınız bir şey sizin için hayırlıdır» (Bakara Suresi)",
"«Allah bir kimseyi ancak gücünün yettiği şeyle yükümlü kılar» (Bakara Suresi)",
"«Şüphesiz Allah'ın rahmeti iyilik yapanlara yakındır» (A'râf Suresi)",
"«Dikkat edin, Allah'ın dostlarına korku yoktur, onlar üzülmeyeceklerdir de» (Yûnus Suresi)",
"«O, nerede olursanız olun sizinle beraberdir» (Hadîd Suresi)",
"«Allah, koruyanların en hayırlısı ve merhametlilerin en merhametlisidir» (Enbiyâ Suresi)",
"«Sabret, çünkü Allah'ın vaadi haktır» (Mü'minûn Suresi)",
"«Ve ölmeyen diri olan Allah'a tevekkül et» (Hûd Suresi)",
"«Mü'mnin işine şaşarım: onun bütün işi hayırdır» (Müslim)",
"«Müslüman'a erişen hiçbir yorgunluk, sıkıntı ve diken batması yoktur ki Allah onunla günahlarını affetmesin» (Müttefekun aleyh)",
"«Şüphesiz Allah, sabreden ve öfkesini yutanları sever» (Müslim)",
"«Dilin, Allah'ı anmakla hep ıslak olsun» (Buhârî)",
"«Allah'ım, Sen affedicisin, cömertsin, affı seversin; beni affet» (Tirmizî)",
"«Senden başka ilâh yoktur, Sen eksiklikten münezzehsin, doğrusu ben zalimlerden oldum» (Yûnus'un duası)",
"«Allah bana yeter, O ne güzel vekildir»",
"«Allah kalpleri tutar; tıpkı kuşu ipliğiyle tutan gibi» (Müttefekun aleyh)",
"«Allah lütufkârdır ve her işte yumuşaklığı sever» (Taberânî)",
"«Subhanallâhi ve bihamdihî, Subhanallâhil-Azîm» — dilde hafif, mizanda ağır iki kelime",
"«Sizindeki her nimet Allah'tandır» (Zuhruf Suresi)",
"«Allah gökleri ve yeri, kayıp olmasınlar diye tutar — bırakmaz»",
"«Ben, kulumun Bana olan zannıyla beraberim» (Buhârî, kudsî hadis)",
"Her yağmurdan sonra toprak yeniden yeşerir",
"Gece ne kadar uzun olursa olsun, seni bekleyen bir şafak var",
"Sandığından daha güçlü, tahmin ettiğinden daha cesur ve hayal ettiğinden daha çok sevilensin",
"Yardım istemek zayıflık değildir; cesaretin en samimi hâlidir",
"Güzel söz, kapalı kalpleri açan bir sadakadır",
"Bugün umut eken, yarın gülümsemeler biçer",
"Bu dünyadaki varlığın hepimiz için bir nimettir — iyinin, seviliyorsun",
"Derin bir nefes al… şimdi buradasın; bu tek başına selamlanmaya değer bir başarıdır",
"Yara iyileşir, kalp toparlanır ve hayat ne kadar gecikse de yeniden aydınlanır",
"Daha yükseğe kalkmak için düştün, daha büyük büyümek için acı çektin",
"Seni gerçekten önemseyenler var — onlara doğru tek adım yeter, gerisi bize",
"Kimse zor gününde yalnız kalmasın diye",
"Bugünkü küçük gülümsemen birinin karanlığında ışık olabilir",
"Gözyaşları ruhu arındırır, zaman yarayı yavaş ama emin adımlarla diker",
"Yanan evler yeniden inşa edilir, kalpler de öyle — vakit ayır",
"Ailen ve komşuların senin de destekçisidir; uzanan ellerini reddetme",
"Her acı çeken aile yükünü paylaşacak birini bulur — işte biz buradayız, işte güvenli odamız",
"Gücün, acı duymaman değil; acıya rağmen devam etmendir",
"Yolunu kimseyle kıyaslamayacaksın; her kalbin kendi iyileşme vakti vardır",
"Yara, ışığın içine girdiği kapıdır (Rûmî)",
"Cesaret korkunun yokluğu değil; onu yenmektir (Mandela)",
"Başarı hiçbir zaman kalıcı değildir, başarısızlık öldürücü değildir; asıl önemlisi devam etme cesaretidir (Churchill)",
"Kışın ortasında, içimde yenilmez bir yaz olduğunu keşfettim (Camus)",
"Umut, uyanık insanın rüyasıdır (Aristoteles)",
"Beni öldürmeyen şey beni güçlendirir (Nietzsche)",
"Bin millik yolculuk tek bir adımla başlar (Lao Tzu)",
"Bir ağaç dikmek için en iyi zaman yirmi yıl önceydi; en iyi ikinci zaman şimdiki zamandır (Çin atasözü)",
"Sabır, kurtuluşun anahtarıdır (Arap atasözü)",
"Çalışan kazanır, eken biçer (Arap atasözü)",
"En güzel söz, az ve öz olanıdır",
"Her bulutun arkasında seni bekleyen bir güneş var",
"En uzun gece bile şafakla biter",
"Zaman en değerli varlığındır; bir kısmını kendine suçluluk duymadan ayır",
"Gülümseme hiçbir şeye mal olmaz, çok şey kazandırır",
"Düşmek başarısızlık değildir; yerde kalmak başarısızlıktır (Japon atasözü)",
"Evden önce komşu (Arap atasözü)",
"Allah'ın eli toplulukla beraberdir; zor gününde tek başınaysan, işte burada bir topluluk var",
"Arzu ile hiçbir amaca ulaşılmaz; dünya ancak gece gündüz çalışılarak alınır (Şevkî)",
"Tek bir samimi kalp bütün bir şehri ısıtabilir",
]

RU = [
"«Поистине, в поминании Аллаха обретают покой сердца» (сура «Ар-Ра'д»)",
"«Поистине, за тягостью следует облегчение» (сура «Аш-Шарх»)",
"«Кто побаивается Аллаха, тому Он устраивает выход» (сура «Ат-Талак»)",
"«Обрадуй же терпеливых» (сура «Аль-Бакара»)",
"«Поистине, Аллах — с терпеливыми» (сура «Аль-Бакара»)",
"«Может быть, вам неприятно то, что является благом для вас» (сура «Аль-Бакара»)",
"«Аллах не возлагает на душу сверх её возможности» (сура «Аль-Бакара»)",
"«Поистине, милость Аллаха близка к творящим добро» (сура «Аль-Араф»)",
"«Да, друзья Аллаха не испытывают страха и не печалятся» (сура «Юнус»)",
"«Он — с вами, где бы вы ни были» (сура «Аль-Хадид»)",
"«Аллах — Наилучший хранитель, Милостивейший из милостивых» (сура «Аль-Анбия»)",
"«Терпи, ведь обещание Аллаха — истина» (сура «Аль-Му'минун»)",
"«И уповай на Живого, Который не умирает» (сура «Худ»)",
"«Удивительно положение верующего: всё его дело — благо» (Муслим)",
"«Какая бы усталость, тревога или даже укол колючки ни коснулись мусульманина, Аллах прощает ему за это дурные дела» (два имама)",
"«Поистине, Аллах любит терпеливых и сдержанных» (Муслим)",
"«Пусть язык твой постоянно будет влажным от поминания Аллаха» (Аль-Бухари)",
"«О Аллах, Ты — Прощающий, Щедрый, Ты любишь прощение — прости же меня»",
"«Нет божества, кроме Тебя! Пречист Ты! Поистине, я был из несправедливых» (мольба Юнуса)",
"«Достаточно мне Аллаха, и Он — прекрасный Попечитель»",
"«Поистине, Аллах удерживает сердца, как удерживают птицу за нитку» (два имама)",
"«Поистине, Аллах — Снисходителен и любит мягкость во всяком деле» (Ат-Табарани)",
"«Пречист Аллах и хвала Ему, Пречист Аллах Великий» — лёгкие для языка, тяжёлые на весах слова",
"«Любое благо, что есть у вас, — от Аллаха» (сура «Аз-Зухруф»)",
"«Аллах удерживает небеса и землю, чтобы они не сдвинулись»",
"«Я рядом с мнением раба обо Мне» (Аль-Бухари, священный хадис)",
"После каждого дождя земля заново покрывается зеленью",
"Как бы ни была длинна ночь, тебя ждёт рассвет",
"Ты сильнее, чем думаешь, смелее, чем предполагаешь, и любимее, чем представляешь",
"Просить о помощи — не слабость; это самая искренняя форма смелости",
"Доброе слово — это милостыня, открывающая закрытые сердца",
"Кто сегодня сеет надежду, завтра пожнёт улыбки",
"Твоё присутствие в этом мире — благо для нас всех — будь добрым, ты любим",
"Сделай глубокий вдох… ты здесь сейчас, и одно это — достижение, достойное уважения",
"Рана заживает, сердце восстанавливается, и жизнь вновь светает, как бы ни запаздывала",
"Ты упал, чтобы подняться выше, и страдал, чтобы вырасти больше",
"Есть те, кому ты действительно дорог — одного шага к ним достаточно, остальное — за нами",
"Чтобы никто не оставался один в свой трудный день",
"Твоя маленькая улыбка сегодня может стать светом в чьей-то тьме",
"Слёзы очищают душу, а время зашивает рану медленно, но верно",
"Сгоревшие дома отстраиваются заново — и сердца тоже; не спеши",
"Твоя семья и соседи — тоже твоя опора; не отказывайся от их протянутой руки",
"Каждая пострадавшая семья найдёт того, кто разделит ношу — вот мы, вот наша безопасная комната",
"Твоя сила не в том, чтобы не чувствовать боли, а в том, чтобы идти дальше вопреки ей",
"Не сравнивай свой путь с чужим; у каждого сердца свой срок исцеления",
"Рана — это место, через которое в тебя входит свет (Руми)",
"Храбрость — это не отсутствие страха, а победа над ним (Мандела)",
"Успех не окончателен, провал не смерителен; важно лишь мужество продолжать (Черчилль)",
"В разгар зимы я наконец понял, что во мне живёт непобедимое лето (Камю)",
"Надежда — это мечта бодрствующего (Аристотель)",
"Что меня не убивает, делает меня сильнее (Ницше)",
"Путь в тысячу ли начинается с первого шага (Лао-цзы)",
"Лучшее время посадить дерево было двадцать лет назад; второе лучшее время — сегодня (китайская пословица)",
"Терпение — ключ к избавлению (арабская пословица)",
"Кто усердствует, тот достигает; кто сеет, тот пожинает (арабская пословица)",
"Лучшая речь — та, что кратка и ясна",
"За каждой тучей ждёт солнце",
"Даже самая длинная ночь заканчивается рассветом",
"Время — самое ценное твоё достояние; удели его часть себе без чувства вины",
"Улыбка ничего не стоит, но даёт многое",
"Падение — не провал; провал — остаться лежать на земле (японская мудрость)",
"Сначала сосед, потом дом (арабская пословица)",
"Рука Аллаха — с общиной; одинок в трудный день? Здесь тебя ждёт община",
"Желаниями целей не достигают; мир берут упорным трудом день и ночь (Шауки)",
"Одно искреннее сердце способно согреть целый город",
]

ZH = [
"「真的，一切心灵因纪念真主而安宁」（《雷霆章》）",
"「与艰难相伴的，确是容易」（《开拓章》）",
"「谁敬畏真主，他将为谁辟一条出路」（《离婚章》）",
"「你向坚忍的人们报喜吧」（《黄牛章》）",
"「真主确是同坚忍者在一起的」（《黄牛章》）",
"「或许你们厌恶某件事，而那件事对你们是有益的」（《黄牛章》）",
"「真主只依各人的能力而加以责成」（《黄牛章》）",
"「真主的慈恩确是临近行善者的」（《高处章》）",
"「真的，真主的朋友们，将来没有恐惧，也不忧愁」（《优努斯章》）",
"「无论你们在哪里，他总是与你们同在」（《铁章》）",
"「真主是最善于保护的，也是至慈的」（《众先知章》）",
"「你当坚忍，因为真主的应许是真实的」（《信士章》）",
"「你当托靠永生不灭的主」（《呼德章》）",
"「信士的事情真奇妙：他的一切都是好的」（穆斯林圣训）",
"「穆斯林所遭遇的疲惫、忧愁、苦难，甚至被刺扎了一下，真主都会以此抵消他的过错」（两大圣训集）",
"「真主确喜爱坚忍而克己的人」（穆斯林圣训）",
"「你当常常以纪念真主使口舌保持湿润」（布哈里圣训）",
"「主啊，你是至赦的、慷慨的，你喜爱饶恕，求你饶恕我」",
"「除你之外，绝无应受崇拜者，我赞颂你超绝万物，我确是不义者」（优努斯圣人的祈祷）",
"「真主使我满足，他是美好的监护者」",
"「真主掌管着人心，就像人用线牵住鸟儿一样」（两大圣训集）",
"「真主是仁厚的，他喜爱万事中的温和」（塔巴拉尼圣训）",
"「赞颂真主超绝并感谢他，赞颂伟大的真主超绝」——唇舌轻巧、天平沉重的两句话",
"「凡你们所享受的恩惠，都是从真主降下的」（《金饰章》）",
"「真主维持着天地，以免天地发生变动」",
"「我随着我的仆人对我的猜想而来」（布哈里圣训）",
"每场雨后，大地都会重新长出绿意",
"黑夜再长，也有等待你的黎明",
"你比自己想象的更强大、更勇敢，也比想象中更被爱",
"求助不是软弱；它是最真诚的勇气",
"善言是打开紧闭心灵的施舍",
"今天播种希望的人，明天收获微笑",
"你存在于这个世界，就是我们所有人的福分——保持善良，你被爱着",
"深呼吸……你现在在这里，这本身就值得致敬",
"伤口会痊愈，心会复原，生活无论多迟都会重新亮起来",
"你跌倒，是为了站得更高；你痛苦，是为了长得更大",
"有人真心在乎你——向他们迈出一步就够，剩下的交给我们",
"愿没有人独自度过艰难的一天",
"你今天的一个微笑，可能是别人黑暗中的光",
"眼泪洗涤心灵，时间缓慢却坚定地缝合伤口",
"被烧毁的房子会重建，心也一样——慢慢来",
"你的家人和邻居也是你的依靠；不要拒绝他们伸出的手",
"每个受苦的家庭都能找到分担重担的人——我们在这里，这里是我们的安全房间",
"你的力量不在于感受不到痛苦，而在于痛苦中依然前行",
"不要拿你的旅程和别人比较；每颗心都有自己的愈合时刻",
"伤口是光照进你内心的地方（鲁米）",
"勇敢不是没有恐惧，而是战胜恐惧（曼德拉）",
"成功不是终点，失败也非致命；重要的是继续前行的勇气（丘吉尔）",
"在隆冬，我终于发现，我身上有一个不可战胜的夏天（加缪）",
"希望是清醒者的梦（亚里士多德）",
"凡不能毁灭我的，必使我更强大（尼采）",
"千里之行，始于足下（老子）",
"种一棵树最好的时间是二十年前，其次是现在（中国谚语）",
"忍耐是解脱之钥（阿拉伯谚语）",
"努力者得成功，播种者得收获（阿拉伯谚语）",
"话贵精简（智慧格言）",
"每朵乌云后面，都有等待你的太阳",
"再漫长的黑夜也会迎来黎明",
"时间是你最宝贵的财富；花一些在自己身上，不必内疚",
"微笑不费分文，却价值连城",
"跌倒不是失败；趴在地上不起来才是失败（日本谚语）",
"先选邻居，再选房子（阿拉伯谚语）",
"真主与集体同在；若你在艰难的日子感到孤单，这里有一群人陪着你",
"愿望不能实现目标；世界只属于日夜奋斗的人（邵基）",
"一颗真诚的心，足以温暖一座城",
]

assert len(TR) == 65 and len(RU) == 65 and len(ZH) == 65, (len(TR), len(RU), len(ZH))

for i, q in enumerate(d):
    q["tr"] = TR[i]
    q["ru"] = RU[i]
    q["zh"] = ZH[i]

json.dump(d, open(P, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(f"OK: added tr/ru/zh to {len(d)} quotes")
